### ISSUE TITLE
Ang Ganda Mo

### ISSUE THREAD

**Issue by Taiga74164** [Shichiha/shichihachi#6]
[Chorus]
Tinitigasan na naman ako sa iyong ganda
Dahil sa iyong ganda akoy napatanga
Suso mo na napakalaki parang pakwan
Bote ang yong katawan at pwet mong malaman

Pwede kabang maikama pagkatapos mo dyan
Pagkatapos maginuman magbabanatan
Iietsa ka sa kama tuloy ang tuhogan
Para kang tinapay titi ko ang palaman, tinitigasan

[Verse 1]
Pagdumadaan ka sa aking harapan, di ko malaman kung pano pakakalagan
Aking nararamdaman, dami ko ng dahilan
Di ko malaman kung pano pakakawalan ang
Pinakamatigas na burat sa Pilipinas pati na sa Asia
Tinalo ko pa ang punong narra ( sa tigas )

Kaya naman hindi ito magkasya sa, sa puking ina mo
Napakaganda ng pagkakagawa sayo
Dahil mga mata mo nabighani sayo
Pagnakita ka na nga matigasan ako oh...
Ay! miss, oo nga pala na nanaginip ako na naka hubad kana
Sa kama ko magpapatuhog kana ba, naninigas nato di ko na ma...

[Chorus]
Tinitigasan na naman ako sa iyong ganda
Dahil sa iyong ganda akoy napatanga
Suso mo na napakalaki parang pakwan
Bote ang yong katawan at pwet mong malaman

Pwede ka bang maikama pagkatapos mo dyan
Pagkatapos maginuman magbabanatan
Iietsa ka sa kama tuloy ang tuhogan
Para kang tinapay titi ko ang palaman, tinitigasan

[Verse 2]
Yang ang gusto ko sa Pilipina, napapadala ako sa mga ngiti nya
Sa mga binti nya napakaputi nya na parang artista sana magpatira
[Mamaya pagwala ng ginagawa magpapa Katrina Halili kaba mamaya]
Sige sayaw kana basta wag kang mahiya
Sanay kana siguro kahit hindi naka higa you!
Alam mo naman na lalaki lang ako dami ko kinahiligan pero puki mo gusto
[Roromansahin kita na para bang si Hayden Kho]
Bibigay ko sayo lahat, ipapakain ko sayo dahil, sayo lang ako unang tinigasan
Sayo ko lang ipuputok pag ako nilabasan
Naka hubad na tayo parang si Eva't Adan, kaya ngayon...

**Comment by Shichiha** [comment]
lamat po
